baseURL = "https://www.lapro.io/blog/"
languageCode = "en-us"
theme = "hugo-serif-theme"
title = "Lapro "
[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 4
[[menu.main]]
name = "Testimonials"
url = "/testimonials/"
weight = 3
[[menu.main]]
name = "Team"
url = "/team/"
weight = 2
[[menu.main]]
name = "Services"
url = "/services/"
weight = 1
[[menu.main]]
name = "Services2"
url = "/services2/"
weight = 5
[params]
